In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [6]:
data=pd.read_csv(r"D:\\Titanic_Survival_Prediction\\notebook\\data\\Titanic-Dataset.csv")

In [7]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
data.drop(labels=["PassengerId"],axis=1,inplace=True)

In our prediction, we used the columns like 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch'

which give us the prediction of Survived Peples

In [12]:
x = data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]
y = data[['Survived']]

In [13]:
x

     Pclass     Sex   Age  SibSp  Parch
0         3    male  22.0      1      0
1         1  female  38.0      1      0
2         3  female  26.0      0      0
3         1  female  35.0      1      0
4         3    male  35.0      0      0
..      ...     ...   ...    ...    ...
886       2    male  27.0      0      0
887       1  female  19.0      0      0
888       3  female   NaN      1      2
889       1    male  26.0      0      0
890       3    male  32.0      0      0

[891 rows x 5 columns]

In [14]:
y

     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]

##### Categorical and Numerical Columns

In [15]:
categorical_cols=x.select_dtypes(include='object').columns

In [16]:
numerical_cols=x.select_dtypes(exclude='object').columns

In [17]:
numerical_cols

Index(['Pclass', 'Age', 'SibSp', 'Parch'], dtype='object')

In [18]:
categorical_cols

Index(['Sex'], dtype='object')

In [23]:
sex_catagories = ["male","female"]

In [19]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [20]:
num_pipeline=Pipeline(
    
    
    steps=[
        
        ('imputer',SimpleImputer()),
        ('scaler', StandardScaler())
    ]
    
    
)

In [24]:
cat_pipeline=Pipeline(
    
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder',OrdinalEncoder(categories=[sex_catagories]))
    ]
    
)

In [25]:
preprocessor=ColumnTransformer(
    [
        
        ('num_pipeline',num_pipeline,numerical_cols),
        ('cat_pipeline',cat_pipeline,categorical_cols)
    ]
)

In [27]:
## Train test split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [29]:
preprocessor.fit_transform(x_train)

array([[-1.61413602,  1.2322632 , -0.47072241, -0.47934164,  0.        ],
       [-0.40055118, -0.50048197, -0.47072241, -0.47934164,  0.        ],
       [ 0.81303367,  0.1926161 , -0.47072241, -0.47934164,  0.        ],
       ...,
       [ 0.81303367,  0.88571416,  1.23056874, -0.47934164,  0.        ],
       [-1.61413602, -1.19358003,  0.37992316,  2.04874166,  1.        ],
       [-1.61413602, -0.65450376, -0.47072241,  0.78470001,  0.        ]])

In [31]:
preprocessor.transform(x_test)

array([[ 8.13033667e-01,  2.73597664e-16,  3.79923164e-01,
         7.84700011e-01,  0.00000000e+00],
       [-4.00551178e-01,  1.15605203e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -7.31514655e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01, -1.80966720e+00, -4.70722410e-01,
         7.84700011e-01,  1.00000000e+00],
       [ 8.13033667e-01, -1.19358003e+00,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00, -2.69449278e-01, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -1.03955824e+00,  1.23056874e+00,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -1.03955824e+00, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00, -8.08525551e-01, -4.70722410e-01,
         2.04874166e+00,  1.00000000e+00],
       [-1.61413602e+00,  5.77670580e-01,  3.79923164e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  1.11674685e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16,  2.08121431e+00,
         7.84700011e-01,  1.00000000e+00],
       [ 8.13033667e-01,  3.85943068e-02, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  5.00659684e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00, -1.03955824e+00, -4.70722410e-01,
         7.84700011e-01,  1.00000000e+00],
       [-1.61413602e+00,  9.62725061e-01,  3.79923164e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-4.00551178e-01, -1.92438382e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  1.34777954e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -4.23471070e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  3.46637891e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -8.08525551e-01,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -7.31514655e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -1.50162362e+00,  2.08121431e+00,
         2.04874166e+00,  0.00000000e+00],
       [-1.61413602e+00,  8.08703268e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  1.15605203e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -1.96368899e+00,  2.08121431e+00,
         2.04874166e+00,  0.00000000e+00],
       [ 8.13033667e-01,  1.15605203e-01, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -8.08525551e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -5.77492862e-01, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -8.85536447e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -1.92438382e-01,  3.79923164e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00, -1.15427486e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  3.85943068e-02, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01, -6.54503759e-01,  1.23056874e+00,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -3.84165894e-02,  3.79923164e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  1.19375775e+00, -4.70722410e-01,
         7.84700011e-01,  1.00000000e+00],
       [ 8.13033667e-01, -1.03955824e+00,  3.79923164e-01,
         3.31278330e+00,  0.00000000e+00],
       [ 8.13033667e-01, -8.08525551e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -5.00481966e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -4.23471070e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.19489940e+00, -4.70722410e-01,
         2.04874166e+00,  0.00000000e+00],
       [ 8.13033667e-01, -1.88667810e+00,  1.23056874e+00,
         7.84700011e-01,  1.00000000e+00],
       [-1.61413602e+00,  1.73283402e+00,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00],
       [ 8.13033667e-01,  8.08703268e-01,  3.79923164e-01,
         4.57682495e+00,  0.00000000e+00],
       [-1.61413602e+00, -1.42461272e+00,  3.79923164e-01,
         2.04874166e+00,  0.00000000e+00],
       [ 8.13033667e-01,  2.73397567e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00, -8.85536447e-01, -4.70722410e-01,
         2.04874166e+00,  1.00000000e+00],
       [-4.00551178e-01,  1.92616099e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  1.57881223e+00, -4.70722410e-01,
         7.84700011e-01,  1.00000000e+00],
       [-4.00551178e-01,  4.23648788e-01, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -8.08525551e-01, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -6.54503759e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01, -1.27059093e+00, -4.70722410e-01,
         7.84700011e-01,  1.00000000e+00],
       [-4.00551178e-01, -1.15427486e-01,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  2.11788850e+00, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-4.00551178e-01, -6.54503759e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -3.84165894e-02, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -9.62547343e-01,  3.79923164e-01,
         7.84700011e-01,  0.00000000e+00],
       [-1.61413602e+00,  1.73283402e+00,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-4.00551178e-01, -2.69449278e-01,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00],
       [-1.61413602e+00, -8.85536447e-01,  1.23056874e+00,
         2.04874166e+00,  1.00000000e+00],
       [-1.61413602e+00, -2.69449278e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  7.31692372e-01,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00],
       [ 8.13033667e-01, -5.00481966e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  5.00659684e-01,  3.79923164e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  7.70997549e-02, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00, -5.77492862e-01, -4.70722410e-01,
         2.04874166e+00,  1.00000000e+00],
       [-4.00551178e-01,  6.54681476e-01, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01,  8.85714165e-01, -4.70722410e-01,
         2.04874166e+00,  1.00000000e+00],
       [ 8.13033667e-01, -1.03955824e+00,  2.93185988e+00,
         7.84700011e-01,  0.00000000e+00],
       [-4.00551178e-01, -3.84165894e-02, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  8.08703268e-01,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.04087761e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  3.19604105e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  1.15605203e-01,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  3.85943068e-02, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  6.54681476e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -1.57863451e+00, -4.70722410e-01,
         2.04874166e+00,  0.00000000e+00],
       [ 8.13033667e-01, -1.57863451e+00,  2.93185988e+00,
         2.04874166e+00,  1.00000000e+00],
       [-1.61413602e+00,  2.42593209e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -1.15427486e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  1.42479044e+00,  3.79923164e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  1.19375775e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  5.00659684e-01, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -1.92438382e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.65696478e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  4.23648788e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00, -8.08525551e-01,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01,  6.54681476e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  7.70997549e-02, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -3.46460174e-01,  3.79923164e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  8.08703268e-01,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00],
       [-1.61413602e+00,  1.34777954e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  3.85943068e-02, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  8.08703268e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -6.93009207e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  5.00659684e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -7.31514655e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  3.19604105e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  5.00659684e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01, -5.77492862e-01,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00],
       [ 8.13033667e-01,  1.42479044e+00,  3.79923164e-01,
         3.31278330e+00,  1.00000000e+00],
       [-4.00551178e-01, -5.00481966e-01,  1.23056874e+00,
         7.84700011e-01,  0.00000000e+00],
       [-1.61413602e+00,  1.92616099e-01, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  2.57995388e+00,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-4.00551178e-01, -2.20781353e+00, -4.70722410e-01,
         2.04874166e+00,  0.00000000e+00],
       [ 8.13033667e-01, -3.46460174e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  4.23648788e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  1.50180133e+00, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00, -4.23471070e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -6.54503759e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16,  3.79923164e-01,
         7.84700011e-01,  0.00000000e+00],
       [-4.00551178e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -1.88667810e+00, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  1.50180133e+00,  3.79923164e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -1.11656914e+00,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -3.84165894e-02, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  9.62725061e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -8.85536447e-01,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -6.54503759e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  1.11674685e+00,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-4.00551178e-01, -1.15427486e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  5.77670580e-01,  3.79923164e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  7.31692372e-01, -4.70722410e-01,
         5.84086660e+00,  1.00000000e+00],
       [-4.00551178e-01,  3.46637891e-01,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00],
       [-4.00551178e-01,  3.85943068e-02, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  2.81098657e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01,  1.03973596e+00, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -4.23471070e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -8.85536447e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [-4.00551178e-01,  5.00659684e-01,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01,  1.92616099e-01,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00],
       [ 8.13033667e-01, -4.61976518e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-4.00551178e-01,  7.31692372e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.73397567e+00, -4.70722410e-01,
         7.84700011e-01,  0.00000000e+00],
       [-4.00551178e-01, -5.00481966e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00,  2.73597664e-16,  3.79923164e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -5.77492862e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  4.23648788e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [-1.61413602e+00, -5.00481966e-01, -4.70722410e-01,
         7.84700011e-01,  0.00000000e+00],
       [-4.00551178e-01, -8.85536447e-01, -4.70722410e-01,
         2.04874166e+00,  1.00000000e+00],
       [-1.61413602e+00,  5.00659684e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01, -1.57863451e+00,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00],
       [ 8.13033667e-01, -9.62547343e-01, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  2.73597664e-16, -4.70722410e-01,
        -4.79341636e-01,  0.00000000e+00],
       [ 8.13033667e-01,  6.54681476e-01,  3.79923164e-01,
         5.84086660e+00,  1.00000000e+00],
       [-4.00551178e-01, -9.62547343e-01, -4.70722410e-01,
        -4.79341636e-01,  1.00000000e+00],
       [ 8.13033667e-01, -1.96368899e+00,  3.79923164e-01,
         7.84700011e-01,  1.00000000e+00]])

In [32]:
preprocessor.get_feature_names_out()

array(['num_pipeline__Pclass', 'num_pipeline__Age', 'num_pipeline__SibSp',
       'num_pipeline__Parch', 'cat_pipeline__Sex'], dtype=object)

In [33]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())
x_test=pd.DataFrame(preprocessor.transform(x_test),columns=preprocessor.get_feature_names_out())

In [34]:
x_train

,num_pipeline__Pclass,num_pipeline__Age,num_pipeline__SibSp,num_pipeline__Parch,cat_pipeline__Sex
0,-1.614136,1.232263e+00,-0.470722,-0.479342,0.0
1,-0.400551,-5.004820e-01,-0.470722,-0.479342,0.0
2,0.813034,1.926161e-01,-0.470722,-0.479342,0.0
3,0.813034,-2.694493e-01,0.379923,-0.479342,0.0
4,0.813034,-1.809667e+00,2.931860,2.048742,1.0
...,...,...,...,...,...
707,0.813034,-6.545038e-01,-0.470722,-0.479342,1.0
708,-1.614136,2.735977e-16,-0.470722,-0.479342,0.0
709,0.813034,8.857142e-01,1.230569,-0.479342,0.0
710,-1.614136,-1.193580e+00,0.379923,2.048742,1.0
711,-1.614136,-6.545038e-01,-0.470722,0.784700,0.0

In [35]:
x_test

,num_pipeline__Pclass,num_pipeline__Age,num_pipeline__SibSp,num_pipeline__Parch,cat_pipeline__Sex
0,0.813034,2.735977e-16,0.379923,0.784700,0.0
1,-0.400551,1.156052e-01,-0.470722,-0.479342,0.0
2,0.813034,-7.315147e-01,-0.470722,-0.479342,0.0
3,-0.400551,-1.809667e+00,-0.470722,0.784700,1.0
4,0.813034,-1.193580e+00,0.379923,-0.479342,1.0
...,...,...,...,...,...
174,0.813034,-9.625473e-01,-0.470722,-0.479342,0.0
175,0.813034,2.735977e-16,-0.470722,-0.479342,0.0
176,0.813034,6.546815e-01,0.379923,5.840867,1.0
177,-0.400551,-9.625473e-01,-0.470722,-0.479342,1.0
178,0.813034,-1.963689e+00,0.379923,0.784700,1.0

In [36]:
# Model training

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [38]:
def evaluate_model(true, predicted):
    acc_score = accuracy_score(true,predicted)
    return acc_score

In [39]:
# Train multiple models

models = {
    "LogisticRegression":LogisticRegression(),
    "RandomForestClassifier" : RandomForestClassifier(),
    "SupportVectorMachine" : SVC(),
    "KNeighborsClassifier" : KNeighborsClassifier()
}

In [41]:
acc_list = []
model_list = []

In [42]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)

    #Make Predictions
    y_pred=model.predict(x_test)

    #this is a validation(test) score
    acc_score=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("Accuracy Score",acc_score)

    acc_list.append(acc_score)
    
    print('='*35)
    print('\n')

LogisticRegression
Model Training Performance
Accuracy Score 0.8156424581005587
===================================


RandomForestClassifier
Model Training Performance
Accuracy Score 0.8212290502793296
===================================


SupportVectorMachine
Model Training Performance
Accuracy Score 0.8100558659217877
===================================


KNeighborsClassifier
Model Training Performance
Accuracy Score 0.8100558659217877
===================================

In [43]:
acc_list

[0.8156424581005587,
 0.8212290502793296,
 0.8100558659217877,
 0.8100558659217877]